xm cobol PANIS    omf (gnt);
xm cobol PANANZ   omf (gnt);
xm cobol PANARTAN omf (gnt);
xm cobol PANDAU   omf (gnt);
xm cobol PANDEBAN omf (gnt);
xm cobol PANLAG   omf (gnt);
xm cobol PANLFDRU omf (gnt);
xm cobol PANLIEF  omf (gnt);
xm cobol PANLIST  omf (gnt);
xm cobol PANRECH  omf (gnt);
xm cobol PANRAST  omf (gnt);
xm cobol PANSTAM  omf (gnt);
xm cobol PANTUED  omf (gnt);
xm cobol PANVORL  omf (gnt);
xm cobol PANBSKOM omf (gnt);
xm cobol PANBS    omf (gnt);
xm cobol PANARCH  omf (gnt);
xm cobol PANDECV  omf (gnt);
XM cobol PAREZ    omf (gnt);
XM cobol PARVORL  omf (gnt);
XM cobol PARDRU   omf (gnt);
XM cobol PARHINW  omf (gnt);
XM cobol PARKOMKA omf (gnt);
XM cobol PAKOKRED omf (gnt);
XM cobol PAKOANZ  omf (gnt);
XM cobol PAREZANL omf (gnt);
XM cobol PARLGKOR omf (gnt);
XM cobol PARCONV  omf (gnt);
XM cobol PANFACV  omf (gnt);
XM cobol PANCVART omf (gnt);
XM cobol PANETIK  omf (gnt);
del *.int
del *.i?0
del *.idy
del *.csi
rem XM run library PAREZ.LBT
XM run library PANIS.LBT
REM XM run library PANBS.LBT
REM XCOPY *.G* \WB\GNT /Y
del *.g*
