xm cobol PANIS    omf (gnt);
xm cobol PANANZ   omf (gnt);
xm cobol PANARTAN omf (gnt);
xm cobol PANDAU   omf (gnt);
xm cobol PANDEBAN omf (gnt);
xm cobol PANLAG   omf (gnt);
xm cobol PANLFDRU omf (gnt);
xm cobol PANLIEF  omf (gnt);
xm cobol PANLIST  omf (gnt);
xm cobol PANRECH  omf (gnt);
xm cobol PANRAST  omf (gnt);
xm cobol PANSTAM  omf (gnt);
xm cobol PANTUED  omf (gnt);
xm cobol PANVORL  omf (gnt);
xm cobol PANBSKOM omf (gnt);
xm cobol PANBSK   omf (gnt);
xm cobol PANARCH  omf (gnt);
XM cobol PAREZ    omf (gnt);
XM cobol PARVORL  omf (gnt);
XM cobol PARDRU   omf (gnt);
XM cobol PARHINW  omf (gnt);
XM cobol PARKOMKA omf (gnt);
XM cobol PAKOKRED omf (gnt);
XM cobol PAKOANZ  omf (gnt);
XM cobol PAREZANL omf (gnt);
XM cobol PARCONV  omf (gnt);
XM COBOL pakoLAG   omf(gnt);
XM COBOL pakoVORL  omf(gnt);
XM COBOL pakoSTAM  omf(gnt);
XM COBOL pakoANZ   omf(gnt);
XM COBOL pakoERF   omf(gnt);
XM COBOL pakoJOUR  omf(gnt);
XM COBOL pakoLIS   omf(gnt);
XM COBOL pakoBIL   omf(gnt);
XM COBOL pakoKRED  omf(gnt);
xm run library PAREZ.LBT
xm run library PANIS.LBT
xm run library PANBS.LBT
xm run library PAKOLAG.LBT
pak a /exe a:PPPP pa*.lbr
del *.csi
del *.aif
del *.int
del *.i?0
del *.idy
del *.g??
